### ISSUE TITLE
Rating service: calculates rating for every pick-up and stores the details in its DB.

### ISSUE THREAD

**Issue by mghlaiel** [creometry-incubator/colibris#26]
- When pick-up is successful, the collector gets to rate it. Collect service sends Rating data (data quality, Quantity, treatment) to rating service.
- Rating service calculates overall Rating and reward points according to a basic average formula (subject to change according to colibris' requirements)
- Rating service stores Details of "rating data" and overall rating per pick-up, Customer, Location, Date, and time.
- Rating service sends newly calculated "overall rating" + "reward points" to User service to update Data in User profile

**Comment by seifb01** [comment]
So we should add a field named overall_rating for each row we create?
Also, can you clarify the last point?

**Comment by seifb01** [comment]
I also don't have the location, date, and time of the pick-up I only have the id. So maybe I should send the result of the calculations to the schedule microservice that has the data for that specific id.
